name: app_store_api_dart_gen
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  openapi_generator_annotations: ^4.0.0

dev_dependencies:
  build_runner:
  openapi_generator: ^4.0.0
  flutter_lints: ^2.0.0
